- name: "node-pool1"
  machine_type: "n1-standard-4"
  # node_locations: 
  #   - us-central1-b
  #   - us-central1-c"
  # autoscaling:
  #     min_node: 2
  #     max_node: 6
  node_count: 2
  local_ssd_count: 0
  disk_size_gb: 1
  disk_type: "pd-standard"
  image_type: "COS"
  auto_repair: true
  auto_upgrade: true
  preemptible: true
  initial_node_count: 1
  accelerator:
    type: 'nvidia-tesla-t4'
    count: 0
